from tkinter import *
def func1(n):
    x = output_var.get()
    output_var.set(x + n)
def show_result()   :
    res = eval(output_var.get())
    output_var.set('')
    output_var.set(res)
root = Tk()
root.title("calculator")
root.config({'bg':"#3cb371"})
root.geometry("400x580")
root.iconbitmap("icon.ico")
output_var = StringVar(value="")
number_var = StringVar()
output_label = Label(root, text="0.0",padx=20, font=("arial", 22),fg="blue",\
    bg="silver", width=20, anchor="w", textvariable=output_var)
output_label.pack(pady=10)
number7 = Button(root, text="7",padx=20,  font=("arial", 22),fg="#ff0000", bg="#ffa500", command=lambda :func1('7'))
number7.place(x=30, y=70)
number8 = Button(root, text="8",padx=20, font=("arial", 22),fg="#ff0000", bg="#ffa500", command=lambda :func1('8') )
number8.place(x=115, y=70)
number9 = Button(root, text="9",padx=20, font=("arial", 22),fg="#ff0000", bg="#ffa500", command=lambda :func1('9'))
number9.place(x=200, y=70)
add_button = Button(root, text="+",padx=20, font=("arial", 22),fg="#ff0000", bg="#ffa500", command=lambda :func1('+'))
add_button.place(x=285, y=70)
eq_button = Button(root, text="=",padx=20, font=("arial", 22),fg="#ff0000", bg="#ffa500", command=lambda :show_result())
eq_button.place(x=285, y=130)
root.mainloop()
